version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'emre1905'
      MYSQL_ROOT_PASSWORD: 'emre1905'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: